services:
  - type: web
    name: api-jwt-security
    env: java
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar target/*.jar
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_VERSION
        value: 17